version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
