---

services:
  web:
    image: ghcr.io/dmptrluke/dash:latest
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./apps.json:/config/apps.json
    environment:
      TZ: Pacific/Auckland

