---
version: "3.8"

services:
  web:
    image: ghcr.io/dmptrluke/dash:latest
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./apps.json:/config/apps.json
    environment:
      TZ: Pacific/Auckland

